sudo: required
dist: trusty
language: php

cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 5.6
env:
  - VERSION=HEAD
  - VERSION=8.x-1.11
  - VERSION=8.x-1.10
  - VERSION=8.x-1.06
  - VERSION=8.x-1.05
  - VERSION=8.x-1.04
  - VERSION=8.x-1.03
  - VERSION=8.x-1.02
  - VERSION=8.x-1.01
  - VERSION=8.x-1.00

addons:
  apt:
    packages:
    # Trusty does not include MySQL by defualt.
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  # Initialize xvfb (see https://docs.travis-ci.com/user/gui-and-headless-browsers)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  # Download Chrome Driver
  - LATEST_CHROMEDRIVER=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - wget http://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - mkdir -p $HOME/.composer/vendor/bin
  - mv -f chromedriver $HOME/.composer/vendor/bin/
  - rm chromedriver_linux64.zip
  # Echo Chrome version
  - google-chrome --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Create the MySQL database and increase the timeout (?)
  - mysql -u root -e 'CREATE DATABASE drupal; SET GLOBAL wait_timeout = 5400;'

  # PHP conf tweaks
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Build the Lightning code base.
  - composer global require phing/phing
  - phing build -Dversion=$VERSION -Dbranch=$TRAVIS_COMMIT

  # Install Lightning.
  - phing install -Ddb.database=drupal
  # Execute database updates if we're not building from HEAD.
  - if [ $VERSION != "HEAD" ]; then phing update; fi

before_script:
  # A harmless diagnostic to ensure the repo is clean.
  - git status
  - cd docroot
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  # Start Selenium and dump its ginormous log into a temporary file.
  - mkdir tmp
  - selenium-server-standalone -port 4444 -log tmp/selenium2.log &
  - sleep 5

script:
  - cd ./profiles/lightning
  - behat --strict --stop-on-failure

matrix:
  fast_finish: true
