dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

php:
  - 7.1

env:
  - VERSION=HEAD
  # The final CI slot should be used to test the update path from the oldest
  # available database fixture.
  - VERSION=3.0.0

matrix:
  fast_finish: true

addons:
  chrome: stable

before_install:
  - composer self-update
  - composer --version
  - google-chrome-stable --version

  - export ORCA=$TRAVIS_BUILD_DIR/../orca
  - export ORCA_FIXTURE=$ORCA-build
  - export ORCA_SUT_NAME=acquia/lightning
  - export ORCA_SUT_BRANCH=8.x-3.x
  - export ORCA_PACKAGES_CONFIG_ALTER=../lightning/tests/packages.yml

  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export PATH="$ORCA/bin:$PATH"
  - export PATH="$ORCA/vendor/bin:$PATH"
  - export PATH="$ORCA_FIXTURE/vendor/bin:$PATH"

  # Install ORCA and prepare the environment.
  - git clone --branch master --depth 1 https://github.com/acquia/orca.git $ORCA
  - $ORCA/bin/travis/before_install.sh

install:
  - $ORCA/bin/travis/install.sh

  # Run ORCA static analysis tools.
  - orca static-analysis:run ./

  # Use ORCA to build the code base.
  - orca fixture:init -f --sut $ORCA_SUT_NAME --core 8.7.x-dev --dev --profile lightning
  # Install dev dependencies.
  - composer require --dev drupal/console --working-dir $ORCA_FIXTURE --no-update
  # Update in a separate step to prevent lock file version conflicts.
  - composer update --working-dir $ORCA_FIXTURE

before_script:
  - cd $ORCA_FIXTURE/docroot
  - $TRAVIS_BUILD_DIR/update.sh $VERSION

script:
  - orca tests:run --sut $ORCA_SUT_NAME

after_failure:
  - drush watchdog:show --count=100 --severity=Error --extended
