dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 7.0
env:
  - VERSION=HEAD
  # Add 3.x fixtures once Lightning Layout 2.x is stable and a migration path
  # from Panels and Panelizer exists.
  # - VERSION=3.0.0

addons:
  chrome: stable

before_install:
  # Tweak PHP configuration.
  - phpenv config-rm xdebug.ini
  - phpenv config-add ./tests/travis.php.ini
  - phpenv rehash

  - composer self-update
  - composer --version
  - google-chrome-stable --version

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

install:
  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - yes '' | pecl install yaml

  # Build the Lightning code base with the latest dependencies.
  - composer update
  # Install Lightning cleanly so that settings.php will be created properly.
  - lightning install --no-dev --from-config 'sqlite\://db.sqlite' lightning 'http://127.0.0.1:8080'
  - lightning make:extender
  # Restore and update from the previous version.
  - lightning update $VERSION
  - drush cache:rebuild

before_script:
  - drush config:set system.date timezone.default '' --yes
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  # Disable the History module during testing, to prevent weird deadlock errors that don't
  # actually affect anything.
  - drush pm-uninstall --yes history
  - chromedriver --port=4444 &
  - cp -f phpunit.xml docroot/core

script:
  - composer validate composer.json --no-check-all --ansi --no-interaction
  - behat --stop-on-failure --tags ~orca_ignore
  - cd docroot
  - phpunit --configuration ./core --group lightning,profiles

after_failure:
  - drush watchdog:show --count=100 --severity=Error --extended

matrix:
  fast_finish: true
