dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 7.0
env:
  - VERSION=HEAD
  - VERSION=3.2.2
  # The final CI slot should be used to test the update path from the oldest
  # available database fixture.
  - VERSION=3.0.0

addons:
  chrome: stable

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - google-chrome-stable --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Create the MySQL database and add a user for testing.
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'lightning'@'localhost' IDENTIFIED BY 'lightning'; GRANT ALL ON drupal.* TO 'lightning'@'localhost';"

  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - yes '' | pecl install yaml
  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Build the Lightning code base with the latest dependencies.
  - composer update
  # Install Lightning cleanly so that settings.php will be created properly.
  - lightning install --from-config 'mysql\://lightning:lightning@127.0.0.1/drupal' lightning 'http://127.0.0.1:8080'
  # Restore and update from the previous version.
  - lightning update $VERSION
  - drush cache:rebuild

before_script:
  - drush config:set system.date timezone.default $TZ --yes
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
  # Disable the History module during testing, to prevent weird deadlock errors that don't
  # actually affect anything.
  - drush pm-uninstall --yes history
  - export MINK_DRIVER_ARGS_WEBDRIVER='["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless","--no-sandbox","--disable-dev-shm-usage","--disable-extensions"]}}, "http://localhost:9515"]'
  - chromedriver &

script:
  - composer validate composer.json --no-check-all --ansi --no-interaction
  - behat --config .behat.yml --stop-on-failure
  - cd docroot
  - phpunit --configuration ./core --group lightning,profiles

after_failure:
  - drush watchdog:show --count=100 --severity=Error --extended

matrix:
  fast_finish: true
