entity_browser.browser.widget.embed_code:
  type: mapping
  label: 'Embed code widget settings'
  mapping:
    submit_text:
      type: string
      label: 'Submit button text'
    form_mode:
      type: string
      label: 'Inline entity form mode'

entity_browser.browser.widget.file_upload:
  type: mapping
  label: 'Upload widget settings'
  mapping:
    submit_text:
      type: string
      label: 'Submit button text'
    form_mode:
      type: string
      label: 'Inline entity form mode'
    return_file:
      type: boolean
      label: 'Return underlying file entity'
