content_roles:
  creator:
    enabled: true
    label: '? creator'
    permissions:
      - 'create ? content'
      - 'edit own ? content'
      - 'view ? revisions'
      - 'view own unpublished content'
      - 'create url aliases'
      - 'access in-place editing'
      - 'access contextual links'
      - 'access toolbar'
      - 'configure any layout'
      - 'use text format rich_text'
      - 'access ckeditor_media_browser entity browser pages'
      - 'access media_browser entity browser pages'
      - 'access image_browser entity browser pages'
      - 'use editorial transition create_new_draft'
      - 'use editorial transition review'
      - 'view any unpublished content'
      - 'view latest version'
      - 'use moderation sidebar'
  reviewer:
    enabled: true
    label: '? reviewer'
    permissions:
      - 'access content overview'
      - 'edit any ? content'
      - 'delete any ? content'
      - 'use editorial transition publish'
      - 'use editorial transition review'
      - 'use editorial transition archive'
      - 'view any unpublished content'
      - 'view latest version'
      - 'access toolbar'
      - 'use moderation sidebar'
_core:
  default_config_hash: s0DQ96S4Q7lvAlNnSv52u3vDsYFN1OSBlqyVP1fd9WA
